apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app: {{ .Values.appName }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.data.DB_USERNAME | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.data.DB_PASSWORD | b64enc }}
  API_KEY: {{ .Values.secrets.data.API_KEY | b64enc }}
